### ISSUE TITLE
Error: __file_ not defined

### ISSUE THREAD

**Issue by nixudos** [vladmandic/sd-extension-system-info#12]
I get following ewrror when trying to use the extension (Windows 10)

Error loading script: system-info.py
Traceback (most recent call last):
  File "C:\SD-Automatic1111\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\SD-Automatic1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\SD-Automatic1111\stable-diffusion-webui\extensions\sd-extension-system-info\scripts\system-info.py", line 29, in <module>
    bench_file = os.path.join(os.path.dirname(__file__), 'benchmark-data-local.json')
NameError: name '__file__' is not defined

**Comment by vladmandic** [comment]
what is the extension verion? try to update it?
correct code is
> bench_file = os.path.join(os.path.dirname(__file__), 'benchmark-data-local.json')

and `__file__` is always defined in python.
