### ISSUE TITLE
[BUG] info tab gone

### ISSUE THREAD

**Issue by brunogcar** [vladmandic/sd-extension-system-info#4]
since commit https://github.com/vladmandic/sd-extension-system-info/commit/579fda3e788455f8f88b960417484016c14c478b, info tab is gone, i dont remember if there was a tab on settings, i guess there is (was) but missing as well

until previous commits when you introduced benchmark and updated ui, it was ok, i tested it

**Comment by vladmandic** [comment]
that means there has to be some error loading the code so it should be printed in console when you start `webui`?

**Comment by brunogcar** [comment]
```
Error loading script: system-info.py
Traceback (most recent call last):
  File "D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\GitHub\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-extension-system-info\scripts\system-info.py", line 3, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

**Comment by vladmandic** [comment]
`pwd` is linux-only package, my bad, fixed and pushed new version.
