### ISSUE TITLE
Trying to load module 'pwd' fails after latest pull

### ISSUE THREAD

**Issue by peacefulpyro** [vladmandic/sd-extension-system-info#5]
I don't think the pwd module is available for folks running Windows.

--

Error loading script: system-info.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\stable-diffusion-webui\extensions\sd-extension-system-info\scripts\system-info.py", line 3, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

**Comment by vladmandic** [comment]
yeah, just figured that out, fixed and pushed new version.
