### ISSUE TITLE
Cant Run Benchmark

### ISSUE THREAD

**Issue by farizy4n** [vladmandic/sd-extension-system-info#54]
I cant run benchmark,  this an error code

`Traceback (most recent call last):
  File "E:\Ai\A1111\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Ai\A1111\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Ai\A1111\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Ai\A1111\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Ai\A1111\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Ai\A1111\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Ai\A1111\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Ai\A1111\webui\extensions\sd-extension-system-info\scripts\system-info.py", line 590, in bench_init
    bench_run([1], False)
  File "E:\Ai\A1111\webui\extensions\sd-extension-system-info\scripts\system-info.py", line 556, in bench_run
    res = run_benchmark(batch, extra)
  File "E:\Ai\A1111\webui\extensions\sd-extension-system-info\benchmark.py", line 35, in run_benchmark
    p = StableDiffusionProcessingTxt2Img(**args)
TypeError: StableDiffusionProcessingTxt2Img.__init__() got an unexpected keyword argument 'detailer'`

**Comment by vladmandic** [comment]
fixed.
next time at very least document where you're trying to use this!
