### ISSUE TITLE
Error on bechmark

### ISSUE THREAD

**Issue by ericko777** [vladmandic/sd-extension-system-info#9]
I'm getting this

--------------------------------
To create a public link, set `share=True` in `launch()`.
Startup time: 12.2s (import torch: 1.7s, import gradio: 1.1s, import ldm: 0.6s, other imports: 1.3s, setup codeformer: 0.2s, load scripts: 1.0s, load SD checkpoint: 5.1s, create ui: 0.8s, gradio launch: 0.1s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.15it/s]
Traceback (most recent call last):█████████████████████████████████████████████████████| 20/20 [00:01<00:00, 17.28it/s]
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\sd-extension-system-info\scripts\system-info.py", line 496, in bench_init
    md = '| ' + ' | '.join(d) + ' |'
TypeError: sequence item 10: expected str instance, builtin_function_or_method found

Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:21<00:00, 17.28it/s]

**Comment by vladmandic** [comment]
Uups. I'll take a look tomorrow, I'm out right now.
